---
- hosts: host

  pre_tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/requirements.yml
    - import_tasks: tasks/install_docker_module.yml
  
  roles:
   - docker-build



  


      
      
      